
variable "application_name" {
  type    = string
  default = "LEMP"
}

variable "application_version" {
  type    = string
  default = "1.0"
}

variable "apt_packages" {
  type    = string
  default = "fail2ban mysql-server nginx php8.0-apcu php8.0-curl php8.0-mysql php8.0-fpm postfix python3-certbot-nginx software-properties-common"
}

variable "do_api_token" {
  type      = string
  default   = "${env("DIGITALOCEAN_API_TOKEN")}"
  sensitive = true
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

locals {
  image_name = "lemp-20-04-snapshot-${local.timestamp}"
}

source "digitalocean" "autogenerated_1" {
  api_token     = "${var.do_api_token}"
  image         = "ubuntu-20-04-x64"
  region        = "nyc3"
  size          = "s-1vcpu-1gb"
  snapshot_name = "${local.image_name}"
  ssh_username  = "root"
}

build {
  sources = ["source.digitalocean.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait"]
  }

  provisioner "file" {
    destination = "/var/"
    source      = "common/files/var/"
  }

  provisioner "file" {
    destination = "/etc/"
    source      = "lemp-20-04/files/etc/"
  }

  provisioner "file" {
    destination = "/var/"
    source      = "lemp-20-04/files/var/"
  }

  provisioner "shell" {
    environment_vars = ["DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    inline           = ["apt -qqy update", "apt -qqy -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' full-upgrade", "apt -qqy -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install software-properties-common", "add-apt-repository -y ppa:ondrej/php", "apt -qqy -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install ${var.apt_packages}", "apt-get -qqy clean"]
  }

  provisioner "shell" {
    environment_vars = ["application_name=${var.application_name}", "application_version=${var.application_version}", "DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    scripts          = ["lemp-20-04/scripts/011-lemp.sh", "common/scripts/014-ufw-nginx.sh", "common/scripts/018-force-ssh-logout.sh", "common/scripts/020-application-tag.sh", "common/scripts/900-cleanup.sh"]
  }

}
