
# could not parse template for following block: "template: hcl2_upgrade:4: function \"TODO\" not defined"

variable "application_name" {
  type    = string
  default = "{{TODO}}"
}

# could not parse template for following block: "template: hcl2_upgrade:4: function \"TODO\" not defined"

variable "application_version" {
  type    = string
  default = "{{TODO}}"
}

# could not parse template for following block: "template: hcl2_upgrade:4: function \"TODO\" not defined"

variable "apt_packages" {
  type    = string
  default = "{{TODO}}"
}

variable "do_api_token" {
  type      = string
  default   = "${env("DIGITALOCEAN_API_TOKEN")}"
  sensitive = true
}

# could not parse template for following block: "template: hcl2_upgrade:4: function \"IMAGE_LABEL\" not defined"

variable "image_name" {
  type    = string
  default = "{{IMAGE_LABEL}}-snapshot-{{timestamp}}"
}

source "digitalocean" "autogenerated_1" {
  api_token     = "${var.do_api_token}"
  image         = "ubuntu-20-04-x64"
  region        = "nyc3"
  size          = "s-1vcpu-1gb"
  snapshot_name = "${var.image_name}"
  ssh_username  = "root"
}

build {
  sources = ["source.digitalocean.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait"]
  }

  provisioner "file" {
    destination = "/var/"
    source      = "common/files/var/"
  }


  # could not parse template for following block: "template: hcl2_upgrade:3: function \"IMAGE_LABEL\" not defined"
  provisioner "file" {
    destination = "/etc/"
    source      = "{{IMAGE_LABEL}}/files/etc/"
  }


  # could not parse template for following block: "template: hcl2_upgrade:3: function \"IMAGE_LABEL\" not defined"
  provisioner "file" {
    destination = "/var/"
    source      = "{{IMAGE_LABEL}}/files/var/"
  }

  provisioner "shell" {
    environment_vars = ["DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    inline           = ["apt -qqy update", "apt -qqy -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' full-upgrade", "apt -qqy -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install ${var.apt_packages}", "apt-get -qqy clean"]
  }

  provisioner "shell" {
    environment_vars = ["application_name=${var.application_name}", "application_version=${var.application_version}", "DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    scripts          = ["common/scripts/014-ufw-http.sh", "common/scripts/018-force-ssh-logout.sh", "common/scripts/020-application-tag.sh", "common/scripts/900-cleanup.sh"]
  }

}
